services:
  ms-autenticacion:
    build: ./ms-autenticacion
    container_name: ms-autenticacion
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=${AWS_RDS_POSTGRES_URL:-jdbc:postgresql://<TU_RDS_ENDPOINT>:5432/innovatech}
      - SPRING_DATASOURCE_USERNAME=${AWS_RDS_POSTGRES_USER:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${AWS_RDS_POSTGRES_PASSWORD:-password}
    networks:
      - innovatech_network

  ms-gestion-proyectos:
    build: ./ms-gestion_proyectos
    container_name: ms-gestion-proyectos
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=${AWS_RDS_POSTGRES_URL:-jdbc:postgresql://<TU_RDS_ENDPOINT>:5432/innovatech}
      - SPRING_DATASOURCE_USERNAME=${AWS_RDS_POSTGRES_USER:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${AWS_RDS_POSTGRES_PASSWORD:-password}
    networks:
      - innovatech_network

  ms-recursos-colaboraciones:
    build: ./ms-recursos_colaboraciones
    container_name: ms-recursos-colaboraciones
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=${AWS_RDS_POSTGRES_URL:-jdbc:postgresql://<TU_RDS_ENDPOINT>:5432/innovatech}
      - SPRING_DATASOURCE_USERNAME=${AWS_RDS_POSTGRES_USER:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${AWS_RDS_POSTGRES_PASSWORD:-password}
    networks:
      - innovatech_network

  ms-analiticas:
    build: ./ms-analiticas
    container_name: ms-analiticas
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATA_MONGODB_URI=${AWS_MONGO_URI:-mongodb://<TU_MONGO_ENDPOINT>:27017/analiticas}
    networks:
      - innovatech_network

  ms-api-gateway:
    build: ./ms-api_gateway
    container_name: ms-api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - ms-autenticacion
      - ms-gestion-proyectos
      - ms-recursos-colaboraciones
      - ms-analiticas
    networks:
      - innovatech_network

networks:
  innovatech_network:
    driver: bridge
