spring:
  application:
    name: ms-gestion_proyectos
  datasource:
    url: jdbc:postgresql://postgres:5432/proyectos_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082
